# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/data/db:/data/db
    ports:
      - 27044:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8044:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
