# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.4.4
    restart: always
    ports:
      - 27044:27017
    volumes:
      - "$(PWD)"/volumes/data/db:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8044:8044
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
